import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    // Essential layout classes
    'min-h-screen',
    'container',
    'mx-auto',
    'px-4',
    'py-8',
    'text-center',
    'font-bold',
    'font-medium',
    'font-semibold',
    
    // Text sizes
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    'text-6xl',
    
    // Colors - Background
    'bg-white',
    'bg-slate-50',
    'bg-slate-100',
    'bg-slate-200',
    'bg-slate-800',
    'bg-slate-900',
    'bg-blue-50',
    'bg-blue-100',
    'bg-blue-600',
    'bg-blue-700',
    'bg-purple-600',
    'bg-purple-700',
    'bg-green-100',
    'bg-green-500',
    'bg-green-600',
    'bg-indigo-100',
    'bg-indigo-600',
    'bg-indigo-900',
    'bg-gray-50',
    'bg-gray-800',
    'bg-red-50',
    'bg-red-900',
    'bg-orange-50',
    'bg-orange-900',
    
    // Colors - Text
    'text-white',
    'text-slate-900',
    'text-slate-800',
    'text-slate-700',
    'text-slate-600',
    'text-slate-500',
    'text-slate-400',
    'text-slate-300',
    'text-slate-200',
    'text-slate-100',
    'text-blue-600',
    'text-blue-400',
    'text-blue-700',
    'text-blue-300',
    'text-purple-600',
    'text-purple-400',
    'text-green-600',
    'text-green-400',
    'text-green-700',
    'text-green-300',
    'text-indigo-600',
    'text-gray-600',
    'text-gray-400',
    'text-gray-900',
    'text-gray-100',
    'text-red-700',
    'text-red-300',
    'text-red-800',
    'text-red-200',
    'text-orange-600',
    'text-orange-400',
    'text-orange-700',
    'text-orange-300',
    
    // Dark mode colors
    'dark:bg-slate-900',
    'dark:bg-slate-800',
    'dark:bg-slate-700',
    'dark:bg-blue-900',
    'dark:bg-purple-900',
    'dark:bg-indigo-900',
    'dark:bg-gray-800',
    'dark:bg-red-900',
    'dark:bg-orange-900',
    'dark:text-slate-100',
    'dark:text-slate-200',
    'dark:text-slate-300',
    'dark:text-slate-400',
    'dark:text-blue-400',
    'dark:text-blue-300',
    'dark:text-purple-400',
    'dark:text-green-400',
    'dark:text-green-300',
    'dark:text-indigo-400',
    'dark:text-gray-100',
    'dark:text-gray-400',
    'dark:text-red-200',
    'dark:text-red-300',
    'dark:text-orange-400',
    'dark:text-orange-300',
    
    // Gradients
    'bg-gradient-to-r',
    'bg-gradient-to-br',
    'from-blue-600',
    'from-slate-50',
    'from-slate-900',
    'from-green-600',
    'from-green-700',
    'to-purple-600',
    'to-purple-700',
    'to-blue-50',
    'to-blue-700',
    'to-indigo-100',
    'to-indigo-600',
    'to-indigo-900',
    'to-slate-800',
    'via-blue-50',
    'via-blue-900',
    'via-purple-600',
    'via-indigo-600',
    'hover:from-blue-700',
    'hover:from-green-700',
    'hover:to-purple-700',
    'hover:to-blue-700',
    
    // Layout
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'md:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'flex',
    'flex-col',
    'flex-row',
    'items-center',
    'justify-center',
    'justify-between',
    'space-x-2',
    'space-x-3',
    'space-x-4',
    'space-y-1',
    'space-y-2',
    'space-y-3',
    'gap-2',
    'gap-3',
    'gap-4',
    'gap-6',
    'gap-8',
    
    // Spacing
    'p-1',
    'p-2',
    'p-3',
    'p-4',
    'p-6',
    'p-8',
    'px-2',
    'px-3',
    'px-4',
    'px-6',
    'px-8',
    'py-1',
    'py-2',
    'py-3',
    'py-4',
    'py-8',
    'py-12',
    'mb-2',
    'mb-4',
    'mb-6',
    'mb-8',
    'mb-12',
    'mt-2',
    'mt-4',
    'mt-6',
    'mt-8',
    'ml-2',
    'mr-2',
    
    // Borders and rounded corners
    'border',
    'border-slate-200',
    'border-slate-700',
    'border-blue-200',
    'border-blue-800',
    'border-purple-200',
    'border-purple-800',
    'border-green-200',
    'border-green-800',
    'border-orange-200',
    'border-orange-800',
    'border-red-200',
    'border-red-800',
    'dark:border-slate-700',
    'dark:border-blue-800',
    'dark:border-purple-800',
    'dark:border-green-800',
    'dark:border-orange-800',
    'dark:border-red-800',
    'rounded-lg',
    'rounded-xl',
    'rounded-2xl',
    'rounded-full',
    
    // Shadows and effects
    'shadow-lg',
    'shadow-xl',
    'hover:shadow-xl',
    'backdrop-blur-sm',
    'backdrop-blur-xl',
    'transition-all',
    'transition-colors',
    'duration-200',
    'duration-300',
    'hover:scale-105',
    'transform',
    
    // Responsive classes
    'hidden',
    'block',
    'sm:inline',
    'sm:hidden',
    'md:block',
    'md:hidden',
    'md:flex',
    'lg:inline',
    'lg:hidden',
    'lg:flex',
    'xl:space-x-2',
    
    // Width and height
    'w-2',
    'w-3',
    'w-8',
    'w-10',
    'w-12',
    'w-16',
    'w-24',
    'w-32',
    'w-fit',
    'h-2',
    'h-3',
    'h-8',
    'h-10',
    'h-12',
    'h-16',
    'h-18',
    'h-20',
    'max-w-2xl',
    'max-w-3xl',
    'max-w-32',
    
    // Positioning
    'sticky',
    'top-0',
    'z-50',
    'relative',
    'absolute',
    
    // Text effects
    'bg-clip-text',
    'text-transparent',
    'whitespace-nowrap',
    'truncate',
    'break-all',
    
    // Interactive states
    'hover:bg-slate-50',
    'hover:bg-slate-200',
    'hover:bg-slate-700',
    'hover:bg-blue-700',
    'hover:bg-purple-700',
    'hover:text-blue-600',
    'hover:text-blue-400',
    'hover:text-blue-700',
    'hover:text-blue-800',
    'hover:text-slate-800',
    'hover:text-slate-100',
    'focus:ring-2',
    'focus:ring-blue-500',
    'focus:ring-offset-2',
    
    // Dark mode hover states
    'dark:hover:bg-slate-800',
    'dark:hover:bg-slate-700',
    'dark:hover:text-blue-400',
    'dark:hover:text-slate-100',
    
    // Special effects
    'animate-in',
    'slide-in-from-top-2',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        // Bond.credit Brand Colors
        brand: {
          primary: '#2c5bff',
          'primary-hover': '#1e4de6',
          'primary-light': '#EEF2FF',
          accent: '#2c5bff',
          'accent-hover': '#1e4de6',
          'accent-light': '#DBEAFE',
        },
        // Bond.credit UI Colors
        ui: {
          background: '#FFFFFF',
          'background-secondary': 'rgba(248, 250, 252, 0.5)',
          'background-tertiary': '#F8FAFC',
          border: '#e2e8f0',
          'border-light': '#f1f5f9',
          card: '#FFFFFF',
          'card-hover': '#f8fafc',
        },
        // Bond.credit Text Colors
        text: {
          primary: '#0f172a',
          secondary: '#475569',
          tertiary: '#64748b',
        },
        // Status Colors
        status: {
          success: '#10B981',
          'success-light': '#D1FAE5',
          warning: '#F59E0B',
          'warning-light': '#FEF3C7',
          error: '#EF4444',
          'error-light': '#FEE2E2',
        },
      },
      fontFamily: {
        heading: ['var(--font-heading)', 'Space Grotesk', 'system-ui', 'sans-serif'],
        sans: ['var(--font-body)', 'Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        body: ['var(--font-body)', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'IBM Plex Mono', 'Consolas', 'monospace'],
      },
      boxShadow: {
        'professional-sm': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        'professional': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'professional-md': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        'professional-lg': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'professional-xl': '0 25px 50px -12px rgba(0, 0, 0, 0.15)',
      },
      borderRadius: {
        'professional': '0.75rem',
        'professional-lg': '1rem',
      },
    },
  },
  plugins: [],
  darkMode: 'class',
}

export default config
